db:
  image: postgres
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_HOST=db
web:
  build: .
  command: mix phoenix.server
  ports:
    - "4000:4000"
  environment:
    - MIX_ENV=dev
    - PORT=4000
  volumes:
    - .:/app
  links:
    - db
test:
  build: .
  command: mix test
  environment:
    - MIX_ENV=test
  volumes_from:
    - web
  links:
    - db
